package com.example.cinema.movie;

public enum Genre {
    ACTION, COMEDY, DRAMA, HORROR, THRILLER, WESTERN, FAMILY, ROMANCE, DOCUMENTARY, ANIMATION, SCI_FI, FANTASY,
    ADVENTURE, MUSICAL, WAR, CRIME, MYSTERY, HISTORICAL, SPORT, SUPERHERO, SPY, NOIR, BIOPIC, DISASTER, SATIRE,
    PSYCHOLOGICAL, PARODY
}
